/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.estacio.poo.historicoacademico.frames;

import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * Projeto de Histórico Acadêmico
 * Atividade Estruturada - 2015.2
 * Programação Orientada a Objetos - Estácio|FIC
 * @author Matheus Braga
 */
public class FramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
        getContentPane().setBackground(new Color(230,230,250));
        setLocationRelativeTo(null);
        addWindowListener(new windowHandler());
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    private void exitAplication() {
        int op = JOptionPane.showConfirmDialog(null, "Realmente deseja sair?", "Encerrar Aplicação", JOptionPane.YES_NO_OPTION);
        if(op == JOptionPane.YES_OPTION)
            System.exit(0);
    }
    
    private class windowHandler extends WindowAdapter {
        
        @Override
        public void windowClosing(WindowEvent e) {
            exitAplication();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmCadastros = new javax.swing.JMenu();
        jmiCadastroAluno = new javax.swing.JMenuItem();
        jmiCadastroUsuario = new javax.swing.JMenuItem();
        jmConsultas = new javax.swing.JMenu();
        jmiConsultaAluno = new javax.swing.JMenuItem();
        jmiConsultaUsuario = new javax.swing.JMenuItem();
        jmiConsultaHistorico = new javax.swing.JMenuItem();
        jmSistema = new javax.swing.JMenu();
        jmiSobre = new javax.swing.JMenuItem();
        jmiSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        desktopPane.setForeground(new java.awt.Color(238, 54, 54));

        jmCadastros.setText("Cadastros");

        jmiCadastroAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/estacio/poo/historicoacademico/imagens/alunos.png"))); // NOI18N
        jmiCadastroAluno.setText("Alunos");
        jmiCadastroAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastroAlunoActionPerformed(evt);
            }
        });
        jmCadastros.add(jmiCadastroAluno);

        jmiCadastroUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/estacio/poo/historicoacademico/imagens/users.png"))); // NOI18N
        jmiCadastroUsuario.setText("Usuários");
        jmiCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastroUsuarioActionPerformed(evt);
            }
        });
        jmCadastros.add(jmiCadastroUsuario);

        jMenuBar1.add(jmCadastros);

        jmConsultas.setText("Consultas");

        jmiConsultaAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/estacio/poo/historicoacademico/imagens/alunos.png"))); // NOI18N
        jmiConsultaAluno.setText("Alunos");
        jmiConsultaAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConsultaAlunoActionPerformed(evt);
            }
        });
        jmConsultas.add(jmiConsultaAluno);

        jmiConsultaUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/estacio/poo/historicoacademico/imagens/users.png"))); // NOI18N
        jmiConsultaUsuario.setText("Usuários");
        jmiConsultaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConsultaUsuarioActionPerformed(evt);
            }
        });
        jmConsultas.add(jmiConsultaUsuario);

        jmiConsultaHistorico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/estacio/poo/historicoacademico/imagens/consulta.png"))); // NOI18N
        jmiConsultaHistorico.setText("Histórico Acadêmico");
        jmConsultas.add(jmiConsultaHistorico);

        jMenuBar1.add(jmConsultas);

        jmSistema.setText("Sistema");

        jmiSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/estacio/poo/historicoacademico/imagens/sobre.png"))); // NOI18N
        jmiSobre.setText("Sobre");
        jmiSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSobreActionPerformed(evt);
            }
        });
        jmSistema.add(jmiSobre);

        jmiSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/estacio/poo/historicoacademico/imagens/cancelar.png"))); // NOI18N
        jmiSair.setText("Sair do Sistema");
        jmiSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSairActionPerformed(evt);
            }
        });
        jmSistema.add(jmiSair);

        jMenuBar1.add(jmSistema);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSairActionPerformed
        exitAplication();
    }//GEN-LAST:event_jmiSairActionPerformed

    private void jmiSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSobreActionPerformed
        new FrameSobre(this, true);
    }//GEN-LAST:event_jmiSobreActionPerformed

    private void jmiCadastroAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastroAlunoActionPerformed
        desktopPane.add(new FrameCadastroAluno());
    }//GEN-LAST:event_jmiCadastroAlunoActionPerformed

    private void jmiCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastroUsuarioActionPerformed
        desktopPane.add(new FrameCadastroUsuario());
    }//GEN-LAST:event_jmiCadastroUsuarioActionPerformed

    private void jmiConsultaAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsultaAlunoActionPerformed
        desktopPane.add(new FrameConsultaAluno());
    }//GEN-LAST:event_jmiConsultaAlunoActionPerformed

    private void jmiConsultaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsultaUsuarioActionPerformed
        desktopPane.add(new FrameConsultaUsuario());
    }//GEN-LAST:event_jmiConsultaUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmCadastros;
    private javax.swing.JMenu jmConsultas;
    private javax.swing.JMenu jmSistema;
    private javax.swing.JMenuItem jmiCadastroAluno;
    private javax.swing.JMenuItem jmiCadastroUsuario;
    private javax.swing.JMenuItem jmiConsultaAluno;
    private javax.swing.JMenuItem jmiConsultaHistorico;
    private javax.swing.JMenuItem jmiConsultaUsuario;
    private javax.swing.JMenuItem jmiSair;
    private javax.swing.JMenuItem jmiSobre;
    // End of variables declaration//GEN-END:variables
}
